// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import Pushwoosh from "pushwoosh-react-native-plugin";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Removes the app's already-delivered notifications from the notification centre.
 * @returns {Promise.<boolean>}
 */
export async function ClearNotificationCenter(): Promise<boolean> {
    // BEGIN USER CODE
    Pushwoosh.clearNotificationCenter();
    return true;
    // END USER CODE
}
