// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import Pushwoosh from "pushwoosh-react-native-plugin";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Schedules a local notification on the device. Local notifications are produced by the
 * app itself and need no network — useful for reminders.
 * @param {string} message - The notification text.
 * @param {Big} afterSeconds - How long to wait before showing it.
 * @param {string} customDataJson - Optional. A JSON object delivered back with the notification.
 * @returns {Promise.<boolean>}
 */
export async function ScheduleLocalNotification(
    message: string,
    afterSeconds?: Big,
    customDataJson?: string
): Promise<boolean> {
    // BEGIN USER CODE
    if (!message) {
        return Promise.reject(new Error("ScheduleLocalNotification: message is required"));
    }

    if (afterSeconds === undefined || afterSeconds === null) {
        return Promise.reject(new Error("ScheduleLocalNotification: afterSeconds is required"));
    }

    if (afterSeconds.lt(0)) {
        return Promise.reject(new Error("ScheduleLocalNotification: afterSeconds must be zero or greater"));
    }

    let userData: Record<string, unknown> | undefined;
    if (customDataJson) {
        try {
            userData = JSON.parse(customDataJson);
        } catch (parseError) {
            return Promise.reject(
                new Error("ScheduleLocalNotification: customDataJson is not valid JSON — " + String(parseError))
            );
        }
    }

    Pushwoosh.createLocalNotification({ msg: message, seconds: Number(afterSeconds), userData });
    return true;
    // END USER CODE
}
