// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import Pushwoosh from "pushwoosh-react-native-plugin";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Returns the user ID currently associated with this device, or an empty string if none is set.
 * @returns {Promise.<string>}
 */
export async function GetUserId(): Promise<string> {
    // BEGIN USER CODE
    return new Promise<string>(resolve => {
        Pushwoosh.getUserId(userId => resolve(userId ?? ""));
    });
    // END USER CODE
}
