// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import Pushwoosh from "pushwoosh-react-native-plugin";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Initializes the Pushwoosh SDK. Call this once, before any other Pushwoosh action —
 * typically from the on-load nanoflow of the app's home page.
 *
 * On Android the FCM Sender ID comes from google-services.json, which the native build
 * picks up; it is not passed here.
 *
 * @param {string} applicationCode - Pushwoosh Application Code, e.g. "XXXXX-XXXXX".
 * @param {string} notificationHandling - Optional. "default" or "manual"; leave empty for default.
 * @returns {Promise.<boolean>}
 */
export async function Initialize(applicationCode: string, notificationHandling?: string): Promise<boolean> {
    // BEGIN USER CODE
    if (!applicationCode) {
        return Promise.reject(new Error("Initialize: applicationCode is required"));
    }

    const config: { pw_appid: string; pw_notification_handling?: string } = { pw_appid: applicationCode };

    if (notificationHandling) {
        config.pw_notification_handling = notificationHandling;
    }

    return new Promise<boolean>((resolve, reject) => {
        Pushwoosh.init(
            config,
            () => resolve(true),
            () => reject(new Error("Initialize: Pushwoosh SDK failed to initialize"))
        );
    });
    // END USER CODE
}
