// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import Pushwoosh from "pushwoosh-react-native-plugin";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Returns the current push token, or an empty string if the device is not registered yet.
 * @returns {Promise.<string>}
 */
export async function GetPushToken(): Promise<string> {
    // BEGIN USER CODE
    return new Promise<string>(resolve => {
        Pushwoosh.getPushToken(token => resolve(token ?? ""));
    });
    // END USER CODE
}
