// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import Pushwoosh from "pushwoosh-react-native-plugin";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Registers the device for push notifications and returns the push token.
 * On iOS this triggers the system permission prompt, so call it at a point in the
 * flow where asking makes sense to the user.
 * @returns {Promise.<string>} The push token.
 */
export async function RegisterForPushNotifications(): Promise<string> {
    // BEGIN USER CODE
    return new Promise<string>((resolve, reject) => {
        Pushwoosh.register(
            token => resolve(token),
            error => reject(error instanceof Error ? error : new Error(String(error)))
        );
    });
    // END USER CODE
}
