// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import Pushwoosh from "pushwoosh-react-native-plugin";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Unregisters the device from push notifications. The device stops receiving pushes
 * until RegisterForPushNotifications is called again.
 * @returns {Promise.<string>} The token the device was unregistered with.
 */
export async function UnregisterForPushNotifications(): Promise<string> {
    // BEGIN USER CODE
    return new Promise<string>((resolve, reject) => {
        Pushwoosh.unregister(
            token => resolve(token),
            error => reject(error instanceof Error ? error : new Error(String(error)))
        );
    });
    // END USER CODE
}
