// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import { NativeModules, Platform } from 'react-native';
import Pushwoosh from 'pushwoosh-react-native-plugin';

// BEGIN EXTRA CODE
/**
 * Every Pushwoosh getter is callback-based and none of them report failure, so a hung
 * or missing native module would leave the diagnostics hanging forever. Each probe gets
 * a deadline and degrades to a marker instead.
 */
function probe(run, fallback, ms = 3000) {
    return new Promise(resolve => {
        let settled = false;
        const finish = (value) => {
            if (!settled) {
                settled = true;
                resolve(value);
            }
        };
        setTimeout(() => finish(fallback), ms);
        try {
            run(finish);
        }
        catch (error) {
            finish(fallback);
        }
    });
}
// END EXTRA CODE

/**
 * @returns {Promise.<string>}
 */
export async function GetDiagnostics() {
	// BEGIN USER CODE
    const nativeModule = NativeModules.Pushwoosh;
    if (!nativeModule) {
        return JSON.stringify({
            nativeModule: "MISSING",
            platform: Platform.OS,
            hint: "The Pushwoosh native module is not in this build. A Make It Native app cannot " +
                "contain it — build a Custom Developer App or a real native build instead."
        }, null, 2);
    }
    const [hwid, pushToken, userId, tags, communicationEnabled, foregroundAlert] = await Promise.all([
        probe(done => Pushwoosh.getHwid(value => done(value !== null && value !== void 0 ? value : "")), "(timed out)"),
        probe(done => Pushwoosh.getPushToken(value => done(value !== null && value !== void 0 ? value : "")), "(timed out)"),
        probe(done => Pushwoosh.getUserId(value => done(value !== null && value !== void 0 ? value : "")), "(timed out)"),
        probe(done => Pushwoosh.getTags(value => done(value !== null && value !== void 0 ? value : {})), {}),
        probe(done => Pushwoosh.isCommunicationEnabled(value => done(Boolean(value))), "(timed out)"),
        probe(done => Pushwoosh.getShowPushnotificationAlert(value => done(Boolean(value))), "(timed out)")
    ]);
    return JSON.stringify({
        nativeModule: "PRESENT",
        platform: Platform.OS,
        osVersion: String(Platform.Version),
        device: {
            hwid,
            pushToken: pushToken || "(not registered)",
            userId: userId || "(not set)"
        },
        settings: {
            communicationEnabled,
            showForegroundAlert: foregroundAlert
        },
        tags
    }, null, 2);
	// END USER CODE
}
