// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import Pushwoosh from 'pushwoosh-react-native-plugin';

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<boolean>}
 */
export async function GetShowForegroundAlert() {
	// BEGIN USER CODE
    return new Promise(resolve => {
        Pushwoosh.getShowPushnotificationAlert(willShow => resolve(Boolean(willShow)));
    });
	// END USER CODE
}
