// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import Pushwoosh from 'pushwoosh-react-native-plugin';

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<string>}
 */
export async function GetTags() {
	// BEGIN USER CODE
    return new Promise((resolve, reject) => {
        Pushwoosh.getTags(tags => resolve(JSON.stringify(tags !== null && tags !== void 0 ? tags : {})), error => reject(error instanceof Error ? error : new Error(String(error))));
    });
	// END USER CODE
}
