// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import Pushwoosh from 'pushwoosh-react-native-plugin';

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} applicationCode
 * @param {string} [notificationHandling]
 * @returns {Promise.<boolean>}
 */
export async function Initialize(applicationCode, notificationHandling) {
	// BEGIN USER CODE
    if (!applicationCode) {
        return Promise.reject(new Error("Initialize: applicationCode is required"));
    }
    const config = { pw_appid: applicationCode };
    if (notificationHandling) {
        config.pw_notification_handling = notificationHandling;
    }
    return new Promise((resolve, reject) => {
        Pushwoosh.init(config, () => resolve(true), () => reject(new Error("Initialize: Pushwoosh SDK failed to initialize")));
    });
	// END USER CODE
}
