// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import Pushwoosh from 'pushwoosh-react-native-plugin';

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} eventName
 * @param {string} [attributesJson]
 * @returns {Promise.<boolean>}
 */
export async function PostEvent(eventName, attributesJson) {
	// BEGIN USER CODE
    if (!eventName) {
        return Promise.reject(new Error("PostEvent: eventName is required"));
    }
    let attributes = {};
    if (attributesJson) {
        try {
            attributes = JSON.parse(attributesJson);
        }
        catch (parseError) {
            return Promise.reject(new Error("PostEvent: attributesJson is not valid JSON — " + String(parseError)));
        }
    }
    Pushwoosh.postEvent(eventName, attributes);
    return true;
	// END USER CODE
}
