// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import Pushwoosh from 'pushwoosh-react-native-plugin';

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} phoneNumber
 * @returns {Promise.<boolean>}
 */
export async function RegisterWhatsappNumber(phoneNumber) {
	// BEGIN USER CODE
    if (!phoneNumber) {
        return Promise.reject(new Error("RegisterWhatsappNumber: phoneNumber is required"));
    }
    Pushwoosh.registerWhatsappNumber(phoneNumber);
    return true;
	// END USER CODE
}
