// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import Pushwoosh from 'pushwoosh-react-native-plugin';

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} message
 * @param {Big} afterSeconds
 * @param {string} [customDataJson]
 * @returns {Promise.<boolean>}
 */
export async function ScheduleLocalNotification(message, afterSeconds, customDataJson) {
	// BEGIN USER CODE
    if (!message) {
        return Promise.reject(new Error("ScheduleLocalNotification: message is required"));
    }
    if (afterSeconds === undefined || afterSeconds === null) {
        return Promise.reject(new Error("ScheduleLocalNotification: afterSeconds is required"));
    }
    if (afterSeconds.lt(0)) {
        return Promise.reject(new Error("ScheduleLocalNotification: afterSeconds must be zero or greater"));
    }
    let userData;
    if (customDataJson) {
        try {
            userData = JSON.parse(customDataJson);
        }
        catch (parseError) {
            return Promise.reject(new Error("ScheduleLocalNotification: customDataJson is not valid JSON — " + String(parseError)));
        }
    }
    Pushwoosh.createLocalNotification({ msg: message, seconds: Number(afterSeconds), userData });
    return true;
	// END USER CODE
}
