// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import Pushwoosh from 'pushwoosh-react-native-plugin';

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} emails
 * @returns {Promise.<boolean>}
 */
export async function SetEmails(emails) {
	// BEGIN USER CODE
    if (!emails) {
        return Promise.reject(new Error("SetEmails: emails is required"));
    }
    const list = emails
        .split(",")
        .map(email => email.trim())
        .filter(email => email.length > 0);
    if (list.length === 0) {
        return Promise.reject(new Error("SetEmails: no valid address in \"" + emails + "\""));
    }
    return new Promise((resolve, reject) => {
        // setEmails reports failures as a plain string, unlike the rest of the API.
        Pushwoosh.setEmails(list, () => resolve(true), error => reject(new Error(error)));
    });
	// END USER CODE
}
