// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import Pushwoosh from 'pushwoosh-react-native-plugin';

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} url
 * @param {string} [headersJson]
 * @returns {Promise.<boolean>}
 */
export async function SetReverseProxy(url, headersJson) {
	// BEGIN USER CODE
    if (!url) {
        return Promise.reject(new Error("SetReverseProxy: url is required"));
    }
    let headers;
    if (headersJson) {
        try {
            headers = JSON.parse(headersJson);
        }
        catch (parseError) {
            return Promise.reject(new Error("SetReverseProxy: headersJson is not valid JSON — " + String(parseError)));
        }
    }
    Pushwoosh.setReverseProxy(url, headers);
    return true;
	// END USER CODE
}
