// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import Pushwoosh from 'pushwoosh-react-native-plugin';

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} tagsJson
 * @returns {Promise.<boolean>}
 */
export async function SetTags(tagsJson) {
	// BEGIN USER CODE
    if (!tagsJson) {
        return Promise.reject(new Error("SetTags: tagsJson is required"));
    }
    let tags;
    try {
        tags = JSON.parse(tagsJson);
    }
    catch (parseError) {
        return Promise.reject(new Error("SetTags: tagsJson is not valid JSON — " + String(parseError)));
    }
    if (typeof tags !== "object" || tags === null || Array.isArray(tags)) {
        return Promise.reject(new Error("SetTags: tagsJson must be a JSON object"));
    }
    return new Promise((resolve, reject) => {
        Pushwoosh.setTags(tags, () => resolve(true), error => reject(error instanceof Error ? error : new Error(String(error))));
    });
	// END USER CODE
}
