// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import Pushwoosh from "pushwoosh-react-native-plugin";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Registers the user's phone number so Pushwoosh can reach them over WhatsApp.
 * @param {string} phoneNumber - In international format, for example +31201234567.
 * @returns {Promise.<boolean>}
 */
export async function RegisterWhatsappNumber(phoneNumber: string): Promise<boolean> {
    // BEGIN USER CODE
    if (!phoneNumber) {
        return Promise.reject(new Error("RegisterWhatsappNumber: phoneNumber is required"));
    }

    Pushwoosh.registerWhatsappNumber(phoneNumber);
    return true;
    // END USER CODE
}
