// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import Pushwoosh from "pushwoosh-react-native-plugin";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Tells whether this device is currently allowed to receive communication from Pushwoosh.
 * Use it to render the state of a privacy toggle.
 * @returns {Promise.<boolean>}
 */
export async function IsCommunicationEnabled(): Promise<boolean> {
    // BEGIN USER CODE
    return new Promise<boolean>(resolve => {
        Pushwoosh.isCommunicationEnabled(isEnabled => resolve(Boolean(isEnabled)));
    });
    // END USER CODE
}
