// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import Pushwoosh from "pushwoosh-react-native-plugin";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Turns communication with Pushwoosh on or off for this device. Switching it off stops
 * all messaging and is the action to wire to a "do not contact me" consent toggle.
 * @param {boolean} enabled - True to allow messaging, false to stop it.
 * @returns {Promise.<boolean>}
 */
export async function SetCommunicationEnabled(enabled: boolean): Promise<boolean> {
    // BEGIN USER CODE
    return new Promise<boolean>((resolve, reject) => {
        Pushwoosh.setCommunicationEnabled(
            enabled,
            () => resolve(true),
            error => reject(error instanceof Error ? error : new Error(String(error)))
        );
    });
    // END USER CODE
}
