// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { NativeModules, Platform } from "react-native";
import Pushwoosh from "pushwoosh-react-native-plugin";

// BEGIN EXTRA CODE
/**
 * Every Pushwoosh getter is callback-based and none of them report failure, so a hung
 * or missing native module would leave the diagnostics hanging forever. Each probe gets
 * a deadline and degrades to a marker instead.
 */
function probe<T>(run: (resolve: (value: T) => void) => void, fallback: T, ms = 3000): Promise<T> {
    return new Promise<T>(resolve => {
        let settled = false;
        const finish = (value: T): void => {
            if (!settled) {
                settled = true;
                resolve(value);
            }
        };

        setTimeout(() => finish(fallback), ms);

        try {
            run(finish);
        } catch (error) {
            finish(fallback);
        }
    });
}
// END EXTRA CODE

/**
 * Collects the state of the Pushwoosh integration into one JSON string: which platform,
 * whether the native module is linked, the device identifiers and the current settings.
 *
 * Meant for support tickets — attach the output rather than describing the symptoms.
 * It contains the device's Pushwoosh IDs, so treat it as you would any device log.
 *
 * @returns {Promise.<string>}
 */
export async function GetDiagnostics(): Promise<string> {
    // BEGIN USER CODE
    const nativeModule = (NativeModules as Record<string, unknown>).Pushwoosh;

    if (!nativeModule) {
        return JSON.stringify(
            {
                nativeModule: "MISSING",
                platform: Platform.OS,
                hint:
                    "The Pushwoosh native module is not in this build. A Make It Native app cannot " +
                    "contain it — build a Custom Developer App or a real native build instead."
            },
            null,
            2
        );
    }

    const [hwid, pushToken, userId, tags, communicationEnabled, foregroundAlert] = await Promise.all([
        probe<string>(done => Pushwoosh.getHwid(value => done(value ?? "")), "(timed out)"),
        probe<string>(done => Pushwoosh.getPushToken(value => done(value ?? "")), "(timed out)"),
        probe<string>(done => Pushwoosh.getUserId(value => done(value ?? "")), "(timed out)"),
        probe<Record<string, unknown>>(done => Pushwoosh.getTags(value => done(value ?? {})), {}),
        probe<boolean | string>(done => Pushwoosh.isCommunicationEnabled(value => done(Boolean(value))), "(timed out)"),
        probe<boolean | string>(
            done => Pushwoosh.getShowPushnotificationAlert(value => done(Boolean(value))),
            "(timed out)"
        )
    ]);

    return JSON.stringify(
        {
            nativeModule: "PRESENT",
            platform: Platform.OS,
            osVersion: String(Platform.Version),
            device: {
                hwid,
                pushToken: pushToken || "(not registered)",
                userId: userId || "(not set)"
            },
            settings: {
                communicationEnabled,
                showForegroundAlert: foregroundAlert
            },
            tags
        },
        null,
        2
    );
    // END USER CODE
}
