// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import Pushwoosh from "pushwoosh-react-native-plugin";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Overrides the language Pushwoosh uses to localise messages for this device.
 * By default the device language is used.
 * @param {string} language - A two-letter code such as "en", "de", "nl".
 * @returns {Promise.<boolean>}
 */
export async function SetLanguage(language: string): Promise<boolean> {
    // BEGIN USER CODE
    if (!language) {
        return Promise.reject(new Error("SetLanguage: language is required"));
    }

    Pushwoosh.setLanguage(language);
    return true;
    // END USER CODE
}
