// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import Pushwoosh from "pushwoosh-react-native-plugin";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Controls whether a push that arrives while the app is open is shown as a system alert.
 * Turn it off to handle foreground pushes yourself through the Pushwoosh events widget.
 * @param {boolean} showAlert - True to show the system alert.
 * @returns {Promise.<boolean>}
 */
export async function SetShowForegroundAlert(showAlert: boolean): Promise<boolean> {
    // BEGIN USER CODE
    Pushwoosh.setShowPushnotificationAlert(showAlert);
    return true;
    // END USER CODE
}
